#!/usr/bin/env python

# Copyright (C) 2012, Aleksey Lim
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
from os.path import join
from gettext import gettext as _

import gevent

import active_document as ad
from local_document import application, optparse, sugar, env
from local_document.mounts import Mounts
from local_document.server import Server
from sugar_network_server import resources


VERSION = '0.1'

SUGAR_REGISTRATION_TIMEOUT = 5


class Application(application.Daemon):

    server = None
    mounts = None

    def run(self):
        while not sugar.has_pubkey():
            logging.info(_('No Sugar SSH key, will start in %s seconds'),
                    SUGAR_REGISTRATION_TIMEOUT)
            gevent.sleep(SUGAR_REGISTRATION_TIMEOUT)

        self.mounts = Mounts(resources.path)
        self.server = Server(self.mounts)

        self.server.serve_forever()

    def shutdown(self):
        self.server.stop()

    def epilog(self):
        if self.mounts is not None:
            self.mounts.close()


# New defaults
application.debug.value = sugar.logger_level()
application.logdir.value = join(env.local_data_root.value, 'logs')
application.rundir.value = join(env.local_data_root.value, 'run')
ad.data_root.value = join(env.local_data_root.value, 'db')

optparse.Option.seek('local-document', env)
optparse.Option.seek('active-document', ad)

app = Application(
        name='sugar-network-service',
        description=_('Sugar Network service'),
        epilog=_('See http://wiki.sugarlabs.org/go/Sugar_Network ' \
                 'for details.'),
        version=VERSION,
        config_files=[
            '/etc/sweets.conf',
            '~/.config/sweets/config',
            sugar.profile_path('sweets.conf'),
            ])
app.start()
