# Copyright (C) 2012-2014 Aleksey Lim
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from sugar_network.model.routes import VolumeRoutes, FrontRoutes


CONTEXT_TYPES = [
        'activity', 'group', 'package', 'book',
        ]
POST_TYPES = [
        'review',       # Review the Context
        'object',       # Object generated by Context application
        'question',     # Q&A request
        'answer',       # Q&A response
        'issue',        # Propblem with the Context
        'announce',     # General announcement
        'update',       # Auto-generated Post for updates within the Context
        'feedback',     # Review parent Post
        'comment',      # Dependent Post
        ]

STABILITIES = [
        'insecure', 'buggy', 'developer', 'testing', 'stable',
        ]

RATINGS = [0, 1, 2, 3, 4, 5]

RESOURCES = (
        'sugar_network.model.context',
        'sugar_network.model.post',
        'sugar_network.model.release',
        'sugar_network.model.report',
        'sugar_network.model.user',
        )
